#' Preforms prediction intervals for each mode.
#' 
#' With this function, the user can preform prediction intervals for response value in each
#'  `x` point from a `malla` object generated by the `mallador` function.
#' 
#'
#' @param muestra Matrix which contains the data points.
#' 
#' @param modas List of vector which contains the modes on each covariable point of `malla`. In case `modas` missing, the function calls `PMSc` to compute them.
#' 
#' @param X Matrix of covariable data points in case `muestra` not present.
#' 
#' @param Y Vector with response values in case `muestra` not present.
#' 
#' @param dim Dimension of covariable.
#' 
#' @param malla Matrix of points used to compute the modes using the Partial Mean-Shift algorithm. If not provided, function calls  `mallador` to compute.
#' 
#' @param h1 Smoothing parameter for covariables.
#' 
#' @param h2 Smoothing parameter for response variable.
#' 
#' @param type Numerical argument. "0" to compute pointwise intervals, "1" to uniform intervals or "2" to compute both. By default, preforms both.
#' 
#' @param eps Tolerance of convergence and minimum diference between modes.
#' 
#' @param p Number of significance digits considered to diference modes.
#' 
#' @param conf.level Confidence level of intervals.
#' 
#' 
#' @export

PredPMS <- function(muestra, modas, dim = ncol(muestra) -1, 
                                 X = muestra[,1:dim], Y = muestra[,dim+1], 
                                 malla = mallador(X, Y, dim = dim), 
                                 h1 = 0.4, h2 = 1, n = length(Y), 
                                 eps = 1e-8, p = -log(eps, base = 10), 
                                 conf.level = 0.95){

  
  
  x.malla <- attr(malla,"x.malla")
  k <- attr(malla, "k")
  l <- attr(malla, "len")
  
  if(missing(modas)){
        modas <- PMSc(X,Y,malla = malla,h1 = h1,h2 = h2, p = p, eps = eps, dim = dim,
                  n = n, k = k, l = l)
  }


  malla.aux = mallador(X,Y,x.malla = X,dim = dim)
  aux <- sapply(1:n, function(i) unique(round(unlist(PMS1c(X = X[-i], Y = Y[-i],
                                                                   x = malla.aux[(i-1)*k+1,1:dim],
                                                                   ymalla = malla.aux[(i-1)*k+(1:k),dim+1],
                                                                   h1 = h1, h2 = h2,eps = eps, k = k, n = n)),p-2)))
  
  
  epsh <- stats::quantile(sapply(1:n, function(i) min(abs(Y[i] - aux[[i]]))), conf.level)
  
  if(dim == 1){
    plot(X, Y)
    ni <- sapply(modas, length)
    xg <- rep(x.malla, times = ni)
    yg <- unlist(modas)
    sapply(1:length(xg), function(i) graphics::lines(rep(xg[i],2), c(yg[i]-epsh, yg[i]+epsh), col ="lightgrey", lwd = 1.5))
    graphics::points(xg, yg - epsh, col = "grey", pch = 19, cex = 0.4)
    graphics::points(xg, yg + epsh, col = "grey", pch = 19, cex = 0.4)
    graphics::points(xg, yg, col = "red", pch = 19 )
  }
}